// Forward prototypes for all modularized functions (replicates the
//  auto-prototyping the Arduino IDE does for .ino files, so header
//  include order never matters). Auto-generated.
#pragma once

void drawGridSquare(int r1,int c1,int r2,int c2,CRGB colour);
void drawHSeg(int R,int C,CRGB col);
void drawVSeg(int R,int C,CRGB col);
static inline int iabs(int v);
static inline float frand();
void fillCell(int row,int col,CRGB c);
void clearFrame();
void smArc(float cy,float cx,float rad,CRGB col,int quad);
void fxAdd(bool isX,int strip,int led,CRGB c,float f);
void fxSplat(float px,float py,float rad,float aa,CRGB col);
void fxStreak(float x0,float y0,float x1,float y1,float rad,float aa,CRGB col);
void fxRing(float cx,float cy,float rad,float thick,float aa,CRGB col);
void fxNebula(uint32_t at,uint8_t hue,uint8_t sat,float scale,float tspd,float radius,float gain);
void fxPlanet(float cx,float cy,float r,uint8_t hue,uint8_t sat,float lx,float ly,uint16_t rot);
int glyphIndex(char c);
void drawGlyphW(uint16_t s,int topR,int C,CRGB col);
int textLenNodes(const char* s);
void drawTextCells(const char* s,int leftC,int topR,CRGB col);
uint8_t seg7(char c);
void drawGlyph1(uint8_t s,int topR,int C,CRGB col);
void drawText1Centered(const char* s,int topR,CRGB col);
void triggerOverlay(uint32_t t,int idx);
void triggerOverlayMood(uint32_t t,uint8_t mood);
void drawNumberTopRight(uint32_t t);
void anim_heartbeat(uint32_t t);
void anim_binaryRain(uint32_t t,float dt);
void anim_tectonic(uint32_t t);
void anim_vortex(uint32_t t);
void anim_earthquake(uint32_t t);
void anim_dnaHelix(uint32_t t);
void anim_supernova(uint32_t at);
void anim_acidTrip(uint32_t t);
void anim_blackHole(uint32_t t);
void anim_wormhole(uint32_t t);
void anim_mitosis(uint32_t t);
void anim_solarFlares(uint32_t t);
void anim_collider(uint32_t t);
void anim_mandala(uint32_t t);
void anim_shockwaveChain(uint32_t t);
void anim_dualVortex(uint32_t t);
void anim_collapsingFunnel(uint32_t t);
void anim_pulsar(uint32_t t);
void anim_liquidMetal(uint32_t t);
void anim_quantumFoam(uint32_t t);
void anim_iceCrown(uint32_t t);
void anim_deepAbyss(uint32_t t);
void anim_coriolisStorm(uint32_t t);
void anim_fibonacci(uint32_t t);
void anim_crystalFracture(uint32_t t);
void anim_aurora(uint32_t t);
void anim_lavaLamp(uint32_t t,float dt);
void anim_nerveSystem(uint32_t t,float dt);
void anim_gravityLens(uint32_t t);
void anim_tidalWave(uint32_t t);
void anim_cymatics(uint32_t t);
void anim_starfieldWarp(uint32_t t,float dt);
void anim_magneticField(uint32_t t);
void anim_pendulumChaos(uint32_t t,float dt);
void anim_darkMatter(uint32_t t);
void anim_squareTunnel(uint32_t t);
void anim_concentricSquares(uint32_t t);
void anim_squareRain(uint32_t t);
void anim_fourfoldSymmetry(uint32_t t);
void anim_diamondPulse(uint32_t t);
void anim_checkerboardMelt(uint32_t t);
void anim_gameOfLife(uint32_t t);
void anim_rotatingCube(uint32_t t);
void anim_squareBreathing(uint32_t t);
void anim_fractalSquares(uint32_t t);
void anim_silk(uint32_t t);
void anim_deepBreath(uint32_t t);
void anim_sunsetHorizon(uint32_t t);
void anim_oilSlick(uint32_t t);
void anim_emberGlow(uint32_t t);
void anim_depthMap(uint32_t t);
void anim_northernMist(uint32_t t);
void anim_moltenGold(uint32_t t);
void anim_cosmicDust(uint32_t t);
void anim_heartglow(uint32_t t);
void evoInit_fn(uint32_t t);
void evoStep(uint32_t t);
CRGB evoColour(float x, float y, uint32_t t);
void anim_evolution(uint32_t t);
void morphInit_fn(uint32_t t);
void morphStep(uint32_t t);
CRGB morphColour(float x, float y, uint32_t t);
void anim_morph(uint32_t t);
void wvInitFn();
void wvDrop(int cx,int cy,float amplitude);
void wvStep();
void anim_wavePhysics(uint32_t t);
void anim_reactionDiffusion(uint32_t t);
void anim_strangeAttractor(uint32_t t,float dt);
void anim_harmonicResonance(uint32_t t, float dt);
void nfInitFn();
void nfStep();
void anim_neuralFire(uint32_t t);
void anim_continuousCA(uint32_t t);
void plInitFn();
void plStrikeBolt(int startX,int startY);
void plStep(float dt);
void anim_plasmaLightning(uint32_t t,float dt);
void anim_agentField(uint32_t t,float dt);
void drawIcon(const uint16_t rows[11],CRGB c);
void tetCells(int s,int r,int8_t out[4][2]);
bool tetFitsCells(int8_t cells[4][2],int row,int col);
float tetEval(uint8_t bd[11][11],int lines);
void tetPlan();
void tetNew();
void anim_tetris(uint32_t at,float dt);
bool snOccupied(int r,int c,int upto);
void snakeFood();
void snakeReset();
void anim_snake(uint32_t at,float dt);
void anim_iconShow(uint32_t at);
void anim_bouncingLogo(uint32_t at,float dt);
void anim_starTunnel3D(uint32_t at,float dt);
void anim_rippleRain(uint32_t at,float dt);
void anim_spiralGalaxy(uint32_t t);
void anim_plasmaField(uint32_t t);
void anim_breatheGradient(uint32_t t);
void anim_boids(uint32_t at,float dt);
void anim_fireworks(uint32_t at,float dt);
void anim_reactionDiff(uint32_t at,float dt);
void anim_setupGrid(uint32_t t);
void anim_scrollBanner(const char* s,uint32_t at,uint8_t baseHue);
void anim_textTOGA(uint32_t at);
void anim_textCASTLE(uint32_t at);
void anim_text2026(uint32_t at);
void rnDrawObstacle(int t,int ox,int GND);
void anim_stickman(uint32_t at,float dt);
void anim_paddleBall(uint32_t at,float dt);
void drawEye(int r,int c,int shape,CRGB col);
void anim_smiley(uint32_t at);
bool eyePixel(float x,float y,float gx,float gy,float bp,CRGB &out);
void anim_eye(uint32_t at,float dt);
static inline float fxfract(float x);
static inline float fxhash(float n);
void anim_starfield2(uint32_t at);
void anim_warp(uint32_t at);
void anim_asteroids(uint32_t at);
void anim_shootingStars(uint32_t at);
void anim_blackHole2(uint32_t at);
void anim_pulsar2(uint32_t at);
void anim_pulsarNebula(uint32_t at);
void anim_orionNebula(uint32_t at);
void anim_horsehead(uint32_t at);
void anim_twinStars(uint32_t at);
void anim_planets(uint32_t at);
void anim_earthWindow(uint32_t at);
void anim_shipPanel(uint32_t at);
void anim_radar(uint32_t at);
void anim_sineWaves(uint32_t at);
void anim_rocketFire(uint32_t at);
void anim_warningLight(uint32_t at);
void anim_aliens(uint32_t at);
void fxInvader(float cx,float cy,uint8_t hue,int frame);
void anim_spaceInvaders(uint32_t at);
void anim_rain2(uint32_t at);
void anim_levitate(uint32_t at);
void anim_confetti(uint32_t at);
void anim_spiralEject(uint32_t at);
void anim_clouds3d(uint32_t at);
void anim_pulseHeart(uint32_t at);
void anim_rainUp(uint32_t at);
void anim_starsFlying(uint32_t at);
void anim_firework2(uint32_t at);
void anim_hStripesFlow(uint32_t at);
void anim_vuColumns(uint32_t at);
void anim_vuGrid(uint32_t at);
